### PR TITLE
Migrate to protobuf v3

### PR DESCRIPTION
**Pull request by nyurik**
Migrate to the v3 of the protobuf crate, and a few minor cleanups.

MSRV is now 1.60.0 due to protobuf lib requirements

### CODE REVIEW

**Comment by b-r-u** [comment]
Thanks so much for this! Your commits include very sensible decisions. I also like the new protobuf API better.

**Comment by b-r-u** [comment]
I conducted some performance tests of v3 vs. v2:
* Runtime performance did not change significantly :neutral_face: 
* Clean compilation time increased a lot (from 25 sec to 40 sec, for me) :disappointed: 
* Binary size decreased (I tested the `count` example) :slightly_smiling_face: 
  * Standard release mode: from 5.9 MB to 4.2 MB
  * Release mode with strip, lto and 1 codegen unit: from 1.5 MB to 0.5 MB

**Comment by nyurik** [comment]
Good news (1st and 3rd), and "that's life" news - 2nd (there were a lot of changes in protobuf-v3 it seems, and they might be using a lot of new sub-deps that also need to be compiled (?)). Protobuf crate has `with-bytes` feature -- maybe it will be more efficient with it?  No idea how that works though.

**Comment by nyurik** [comment]
P.S. Thanks for doing the testing!!!

**Comment by b-r-u** [comment]
Yes, it looks like the main cause for the increased compile times is the number of compilation units (86 vs. 46).

**Pull request merged**
